dependencies:
- name: renku-core
  alias: core
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.11.1
- name: renku-ui
  alias: ui
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.11.0-a6fe6fe
- name: renku-notebooks
  alias: notebooks
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.8.0-2481eb1
- name: renku-gateway
  alias: gateway
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.9.0-cb2a149
- name: gitlab
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.5.2
  condition: gitlab.enabled
- name: renku-graph
  alias: graph
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 1.3.0
  condition: graph.enabled
- name: postgresql
  version: 9.1.1
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
- name: keycloak
  version: 4.10.1
  repository: "@stable"
  condition: keycloak.enabled
